deepgnn:
  batch_size: 140
  num_epochs: 100
  mode: train
  feature_idx: 1
  feature_dim: 50
  label_idx: 0
  label_dim: 121
  seed: 123
  backend: snark
  graph_type: local
  converter: skip
  learning_rate: 0.005
  node_type: 0
  max_id: -1
  log_by_steps: 1
  use_per_step_metrics: true
  storage_type: memory
