defaults:
  - deepgnn/cora

deepgnn:
  num_epochs: 100
  mode: train
  node_type: 0
  seed: 123
  backend: snark
  graph_type: local
  converter: skip
  max_id: -1
  log_by_steps: 1
  use_per_step_metrics: true
  storage_type: memory
